index.html, script.js, styles.css
This PR resolves the issue "Make Landing Page Mobile Responsive" by updating the layout to adapt smoothly across various screen sizes using CSS.
**Changes Made**
- Implemented responsive design using Tailwind utility classes
- Adjusted spacing, layout, and font sizes for smaller screens
- Ensured proper alignment and readability on mobile devices
**Screenshots**
**Related Issue**
Closes #4 
If you need any further assistance or adjustments, feel free to let me know!
=> Responsive landing page

index.html, script.js, styles.css
**Title:**
✨ Added Dark/Light Mode Toggle Functionality
**Description:**
This PR introduces a theme toggle feature that allows users to switch between dark and light modes. It enhances user experience by supporting personalization based on user preference or system settings.
**Changes Included:**
- Implemented dark/light mode toggle logic
- Added necessary styles for both themes
- Updated UI components to support both themes
**Preview:**
https://github.com/user-attachments/assets/3b885391-3d32-4ad2-b65b-211a4a68b41e
Closes #5 
If you need any further assistance or adjustments, feel free to let me know!
=> Added dark - Light mode functionality

styles.css
=> Removed Shadows from the nav bar

index.html, styles.css
This PR adds a new footer section to the website with a contributors message.
change:
- Add  a ` <footer>` element in `index.html`
- Styled the footer in `style.css`
- made it responsive for all screens.
This is a part of GirlScript summer of code 2025 contribution.
=> ✨ Added footer section with contributors message

components/Header.html, index.html, pages/about.html, pages/overview.html, styles.css, styling/overview.css
Created two new static pages — admin.html and overview.html — located inside a new pages/ folder. These additions align with the layout and style of index.html to maintain design consistency. Also added a new CSS file for shared styling and included smooth transitions for a more interactive user experience.
💡 Motivation:
This PR sets the foundation for:
Admin Tools: A dedicated space for managing uploaded notes and user moderation.
Overview Page: Clearly explains platform features, the product roadmap, and usage guidelines for new users.
These improvements support scalability and better user role management (e.g., students, admins, contributors).
✅ Changes Made:
Created pages/admin.html and pages/overview.html
Added styles/overview.css for additional styling and transitions
Included …
=> Add Static Pages and Enhance Routing for NotesVault

index.html, script.js, search.html, styles.css, styles.scss, upload.html
What I Fixed
- Fixed issue with filters not syncing properly on Browse Notes page
- Semester dropdown now shows only 1 and 2
- UI styling of navbar and page matches rest of the site
Issue Linked
Closes #47
Let me know if any improvements are needed 😊
=> fix: resolved Browse Notes bug (closes #47)Browse notes fix

index.html, styles.css
🔧 This PR fixes issue #40
✅ Changes Made:
- Improved CSS for [specific component or page]
- Fixed responsiveness and alignment issues
- Enhanced overall UI consistency
from:
📸 Screenshots: (Attach if needed)
To:
some animations :
=> Fix: CSS bug resolved for issue #40

jotpad.html
Please check all that apply:
Fixed the placeholder in the JotPad editor — it was previously a text .
Also implemented localStorage-based persistence so that users' notes are retained across page refreshes.
These changes significantly improve the user experience of the JotPad.
This update solves two key issues:
- The placeholder was misleading and did not behave like a real placeholder.
- Notes were lost on page refresh, limiting the practicality of the editor.
Now, users can rely on persistent notes and a clean, intuitive writing interface.
Closes #98 
- Typed and refreshed the page to confirm notes persist.
- Verified that placeholder disappears on typing and reappears when cleared.
- checked local storage in dev tools
- Added `id="noteArea"` to the contenteditable div to reference it in …
=> [PR] Fix Placeholder and Add LocalStorage Persistence to JotPad

index.html, styles.css
I have added scroll to top button clicking on which users can reach to top of the page.
Please merge this request.
Solved issue #96
=> Added Scroll to Top button

index.html
I'm Nitin Kumar Patwa, a GSSoC’25 Contributor. 
I noticed that the "Student Account" link in the navigation bar was broken and didn’t redirect to any valid route. This could confuse users and disrupt the overall navigation experience.
What I Fixed:
#Corrected the "Student Account" link to point to the proper route.
This minor fix enhances the usability and ensures smooth access to the student account section.
Looking forward to your feedback!
AFTER
BEFORE
=> 💄 Fix: Broken link to Student Account #124

styling/overview.css
Fixes #102
- Updated text color on the Overview Page for better readability in dark mode.
- Ensured contrast ratios follow accessibility guidelines.
**Before**: Text was barely visible in dark mode  
**After**: Text color now provides proper contrast
---
Let me know if any changes are required. I’m a GSSoC’25 contributor working on this issue.
=> Fix: Improve text visibility on Overview Page in dark mode

about.css, about.html
Complete 'About' page reconstruction with responsive design and CSS fix
Addresses opensource-society#137
- Rebuilt about.html from scratch, adding a comprehensive hero section,
introductory content, detailed feature cards (Mission & Vision, How We Help,
Centralized Notes, Smart Search, Community Powered), and a prominent GitHub
CTA.
- Fixed critical CSS bug in about.css: added missing padding to the .intro-box
class to improve text readability and visual spacing.
- Enhanced responsive design across about.css using media queries, ensuring
optimal layout and usability on mobile, tablet, and desktop devices.
- Corrected relative navigation path for 'about.html' in pages/overview.html
from 'about.html' to '../about.html'.
- Removed extraneous navigation links to maintain the scope of this …
=> Reconstruct 'About' page with comprehensive content, responsive design , and critical CSS padding fix

search.html, styling/search.css
📝 Description:
This PR addresses UI inconsistencies on the Browse Notes page, focusing on layout structure, alignment, and responsiveness. The previous design had uneven spacing and padding, leading to a cluttered visual experience.
🔧 Changes Made:
✅ Fixed margin and padding inconsistencies between note cards and section containers.
✅ Improved overall layout alignment to ensure clean visual flow.
✅ Applied consistent styling across note elements (card containers, headings, buttons).
✅ Aligned and styled navigation elements for a polished appearance.
🎯 Result:
A visually consistent and modern layout.
Better readability and spacing between notes, buttons, and headers.
Seamless user experience across all device sizes.
Screenshots:
After & Before:
=> Enhance Browse Notes Page UI Consistency

index.html, jotpad.html, pages/login.html, pages/overview.html, pages/signup.html, styling/jotpad.css, styling/overview.css, styling/search.css
What’s Fixed(#106): 
Corrected the routing logic in index.html, overview.html, and signup.html.
Ensured buttons and links now navigate to the correct target pages.
Fixed broken or incorrect href paths and button event handlers.
Verified navigation consistency across the site.
📄 Affected Pages:
index.html
overview.html
signup.html
overview.css
login.html
=> Fix Routing Issues Across Multiple Pages

index.html, styles.css
Reverts opensource-society/notesvault#151
=> Revert "Added new hover animation for the navigation links"

index.html, pages/BrowseNotes.html, pages/about.html, pages/overview.html
**Description:**
This PR introduces a new "Browse Notes" page and updates the footer across all relevant pages to include links to this new section.
**Key Changes:**
1.  **New Page: `browse-notes.html`**
* Implements the "Browse Notes" functionality, allowing users to view and download notes.
* Includes HTML structure, CSS styling, and JavaScript logic.
* The JavaScript currently uses dummy data to simulate note fetching and display.
* Modal for viewing detailed note information is implemented.
2.  **CSS Styling (`style.css`) Updates:**
* Adjusted the overall website color scheme to match the provided design image, including:
* Light off-white body background.
* Specific colors for the "Welcome Back" banner, "Browse Notes" and "Upload Notes" buttons, and the "Notes Organised by Br" box.
* …
=> Add Browse Notes Page and Footer Links

about.html, index.html, pages/features.html
i have added the features page. please take a look at it . 
thanks 
issue #132
=> add features page

about.css
This PR removes an unnecessary line (=====) from the about.css file that was likely left behind unintentionally. It was not serving any functional or styling purpose and may affect code readability.
This change improves code cleanliness and aligns with proper CSS formatting and project standards.
⸻
🔧 Changes Made:
•	Cleaned up about.css by removing an extra ===== line under the media query section.
⸻
📂 Files Modified:
•	about.css
🧑‍💻 Contribution:
This PR is part of my contribution to GirlScript Summer of Code (GSSoC) 2025.
=> Remove unnecessary ======= line from css

styles.css
This PR enhances the website's visual appeal and interactivity by:
- Implementing a **modern glassmorphic navbar**
- Adding **hover effects** to the signup/login button for better UX
- Applied `backdrop-filter` and `rgba` background to create a **glassy effect** on the navigation bar
- Styled the navbar with **fixed position** and blur for a modern UI
- Added **hover effects** to the signup button using smooth transitions and box shadows
- Modern and sleek visual design
- Responsive and interactive navigation
- Better feedback on clickable UI elements
- before 
- after 
Closes #26
=> ✨ Add hover effect to signup button & Glassy Navbar

styling/upload.css
Fixed missing closing bracket in code of upload.css
closes #356
=> Fixed error in code of upload.css

index.html, pages/todolist.html, scripts/todolist.js, styling/todolist.css
@adityai0 see the complete front end and todo app is updated
=> To-do list added with the Beautful interface and working functionality #issue348 solved

index.html, styling/styles.css
Fixes #355 
Hi @Aditya-Patwa
I'm Utkarsh Kushwaha (GSSoC'25 Contributor)
I’ve fixed the responsiveness issues on the index.html page of NotesVault.
Please review the changes and let me know if any further modifications are needed.
=> Fixed the responsiveness issues on index.html of NotesVault

LEADERBOARD.md, glassy-ui.css, index.html, pages/overview.html, styling/styles.css
This PR includes multiple visual and structural improvements to the NotesVault UI for a more polished and consistent user experience. Key changes:
🔧 Fixed backdrop-filter property placement in glassy-ui.css to ensure consistent application across components.
♻️ Refactored backdrop-filter styles for scrollable areas to improve layout behavior and maintain styling consistency.
🎨 Enhanced header navigation and footer layout, improving alignment, spacing, and overall responsiveness.
🔁 Merged latest updates from main branch to ensure parity.
🛠️ Minor style updates for smoother visual flow and user experience.
This refactor improves the visual consistency and paves the way for future UI scalability. No functionality or logic has been broken or changed.
=> UI Enhancements: Backdrop Filter Fixes, Header/Footer Layout Updates & Styling Improvements

pages/features.html, pages/search.html
- Fixed Home link in search.html (href='index.html' -> href='../index.html')
- Fixed Sign-Up link in search.html (href='pages/signup.html' -> href='signup.html')
- Fixed favicon path in search.html (href='favicon.png' -> href='../assets/index/images/favicon.png')
- Fixed Home link in features.html (href='index.html' -> href='../index.html')
Resolves #426: Home and Sign-Up links not working on search.html
=> Fix: Resolve navigation link issues in search.html and features.html

index.html, styling/styles.css
- Removed duplicate html elements
- Fixed incorrect paths
- Fixed CSS
---
closes #412
=> Fixed incorrect paths, css and removed duplicate html elements

pages/login.html, pages/signup.html
-> Summary
Fixed broken Home button links on Login and Signup pages.
-> Changes
- Updated the 'href' in login.html and signup.html from '../index.html' to 'index.html'.
- This resolves a 404 error when returning to the home page, since all three files are in the same /pages folder.
-> Why
The previous link pointed outside the /pages directory, leading to navigation failure.
-> Notes
Found this project via OSConnect. Tested locally using a live server vs code extension to confirm navigation works correctly.
Closes #713
=> Fix: [Home button Issue 404 Error Solved in Login and Signup Pages]

styling/about.css
Made the Section Pop-out as It improves the User Experience......
Improved the shape and making them look like the ones in the Features Section........
=> Improved UI design in About Section

pages/index.html
Fixed the issue where the "Welcome Back" tab on the home page was unresponsive.
=> Fixed welcomeback bug

components/header.html
Fixes https://github.com/opensource-society/notesvault/issues/876
Fix: mobile navbar auth buttons not redirecting (#876)
Resolves issue #876 where the Login and Sign Up buttons in the mobile navbar were non-functional.  
Added `onclick` handlers to ensure proper redirection and alignment with desktop behavior.
- Implemented `onclick` navigation for mobile Login and Sign Up buttons.
- Ensured consistent redirection across desktop and mobile views.
- Login button now redirects to `login.html`.
- Sign Up button now redirects to `signup.html`.
👨‍💻 Contribution under **GSSoC**
@adityai0  please review it and merge this PR.
=> Fix: mobile navbar auth buttons not redirecting

components/header.html, scripts/login.js, scripts/script.js
This PR resolves the issue where, after a successful login, users were redirected to a missing file and encountered a 404 error.
It also improves the navbar authentication state management to ensure that the correct options (Login / Sign Up or Profile / Logout) are displayed dynamically based on whether the user is logged in.
Fixed login redirection to correctly navigate users to /dashboard after successful login.
Stored logged-in user details in localStorage for session persistence.
Added updateNavbarAuth() to toggle navbar buttons dynamically.
Before login → shows Login and Sign Up.
After login → hides Login/Sign Up, shows Profile and Logout.
Implemented logout functionality to clear session data and redirect back to the login page.
Added id attributes (nav-login, nav-signup, …
=> Fix login redirect and toggle navbar authentication state
